//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_Integration.DAPAttendanceServiceGroup {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infolog", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Infolog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Attendance_Integration.DAPAttendanceServiceGroup.InfologEntry[] EntriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Attendance_Integration.DAPAttendanceServiceGroup.InfologEntry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologEntry", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class InfologEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Attendance_Integration.DAPAttendanceServiceGroup.InfologType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Attendance_Integration.DAPAttendanceServiceGroup.InfologType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologType", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    public enum InfologType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DAPAttendanceList", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class DAPAttendanceList : Attendance_Integration.DAPAttendanceServiceGroup.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HcmPersonnelNumberIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShiftNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HcmPersonnelNumberId {
            get {
                return this.HcmPersonnelNumberIdField;
            }
            set {
                if ((object.ReferenceEquals(this.HcmPersonnelNumberIdField, value) != true)) {
                    this.HcmPersonnelNumberIdField = value;
                    this.RaisePropertyChanged("HcmPersonnelNumberId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineFrom {
            get {
                return this.MachineFromField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineFromField, value) != true)) {
                    this.MachineFromField = value;
                    this.RaisePropertyChanged("MachineFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineTo {
            get {
                return this.MachineToField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineToField, value) != true)) {
                    this.MachineToField = value;
                    this.RaisePropertyChanged("MachineTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShiftNum {
            get {
                return this.ShiftNumField;
            }
            set {
                if ((object.ReferenceEquals(this.ShiftNumField, value) != true)) {
                    this.ShiftNumField = value;
                    this.RaisePropertyChanged("ShiftNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransDate {
            get {
                return this.TransDateField;
            }
            set {
                if ((this.TransDateField.Equals(value) != true)) {
                    this.TransDateField = value;
                    this.RaisePropertyChanged("TransDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProxyBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.KernelInterop")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Attendance_Integration.DAPAttendanceServiceGroup.XppObjectBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Attendance_Integration.DAPAttendanceServiceGroup.DAPAttendanceList))]
    public partial class ProxyBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Attendance_Integration.DAPAttendanceServiceGroup.DAPAttendanceList))]
    public partial class XppObjectBase : Attendance_Integration.DAPAttendanceServiceGroup.ProxyBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="DAPAttendanceServiceGroup.DAPAttendanceServices")]
    public interface DAPAttendanceServices {
        
        // CODEGEN: Generating message contract since message CreateAttandance has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DAPAttendanceServices/CreateAttandance", ReplyAction="http://tempuri.org/DAPAttendanceServices/CreateAttandanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Attendance_Integration.DAPAttendanceServiceGroup.Fault), Action="http://tempuri.org/DAPAttendanceServices/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        Attendance_Integration.DAPAttendanceServiceGroup.CreateAttandanceResponse CreateAttandance(Attendance_Integration.DAPAttendanceServiceGroup.CreateAttandance request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DAPAttendanceServices/CreateAttandance", ReplyAction="http://tempuri.org/DAPAttendanceServices/CreateAttandanceResponse")]
        System.Threading.Tasks.Task<Attendance_Integration.DAPAttendanceServiceGroup.CreateAttandanceResponse> CreateAttandanceAsync(Attendance_Integration.DAPAttendanceServiceGroup.CreateAttandance request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAttandance", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class CreateAttandance {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public Attendance_Integration.DAPAttendanceServiceGroup.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Attendance_Integration.DAPAttendanceServiceGroup.DAPAttendanceList[] _AttendanceList;
        
        public CreateAttandance() {
        }
        
        public CreateAttandance(Attendance_Integration.DAPAttendanceServiceGroup.CallContext CallContext, Attendance_Integration.DAPAttendanceServiceGroup.DAPAttendanceList[] _AttendanceList) {
            this.CallContext = CallContext;
            this._AttendanceList = _AttendanceList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateAttandanceResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class CreateAttandanceResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public Attendance_Integration.DAPAttendanceServiceGroup.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string result;
        
        public CreateAttandanceResponse() {
        }
        
        public CreateAttandanceResponse(Attendance_Integration.DAPAttendanceServiceGroup.Infolog Infolog, string result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DAPAttendanceServicesChannel : Attendance_Integration.DAPAttendanceServiceGroup.DAPAttendanceServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DAPAttendanceServicesClient : System.ServiceModel.ClientBase<Attendance_Integration.DAPAttendanceServiceGroup.DAPAttendanceServices>, Attendance_Integration.DAPAttendanceServiceGroup.DAPAttendanceServices {
        
        public DAPAttendanceServicesClient() {
        }
        
        public DAPAttendanceServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DAPAttendanceServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DAPAttendanceServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DAPAttendanceServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Attendance_Integration.DAPAttendanceServiceGroup.CreateAttandanceResponse Attendance_Integration.DAPAttendanceServiceGroup.DAPAttendanceServices.CreateAttandance(Attendance_Integration.DAPAttendanceServiceGroup.CreateAttandance request) {
            return base.Channel.CreateAttandance(request);
        }
        
        public Attendance_Integration.DAPAttendanceServiceGroup.Infolog CreateAttandance(Attendance_Integration.DAPAttendanceServiceGroup.CallContext CallContext, Attendance_Integration.DAPAttendanceServiceGroup.DAPAttendanceList[] _AttendanceList, out string result) {
            Attendance_Integration.DAPAttendanceServiceGroup.CreateAttandance inValue = new Attendance_Integration.DAPAttendanceServiceGroup.CreateAttandance();
            inValue.CallContext = CallContext;
            inValue._AttendanceList = _AttendanceList;
            Attendance_Integration.DAPAttendanceServiceGroup.CreateAttandanceResponse retVal = ((Attendance_Integration.DAPAttendanceServiceGroup.DAPAttendanceServices)(this)).CreateAttandance(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Attendance_Integration.DAPAttendanceServiceGroup.CreateAttandanceResponse> Attendance_Integration.DAPAttendanceServiceGroup.DAPAttendanceServices.CreateAttandanceAsync(Attendance_Integration.DAPAttendanceServiceGroup.CreateAttandance request) {
            return base.Channel.CreateAttandanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Attendance_Integration.DAPAttendanceServiceGroup.CreateAttandanceResponse> CreateAttandanceAsync(Attendance_Integration.DAPAttendanceServiceGroup.CallContext CallContext, Attendance_Integration.DAPAttendanceServiceGroup.DAPAttendanceList[] _AttendanceList) {
            Attendance_Integration.DAPAttendanceServiceGroup.CreateAttandance inValue = new Attendance_Integration.DAPAttendanceServiceGroup.CreateAttandance();
            inValue.CallContext = CallContext;
            inValue._AttendanceList = _AttendanceList;
            return ((Attendance_Integration.DAPAttendanceServiceGroup.DAPAttendanceServices)(this)).CreateAttandanceAsync(inValue);
        }
    }
}
